advancedComms = {}
advancedComms.Comms = {}
advancedComms.Functions = {}
function advancedComms.Functions.AddComms(cmd, pre, precolor, color, teams)
    advancedComms.Comms[cmd] = {
        ["prefix"] = pre,
        ["prefixColor"] = precolor,
        ["txtColor"] = color,
        ["teams"] = teams
    }
end


/*
    EDIT BELOW

    example setup:
        AddComms("cmd", "prefix", prefixColor, txtColor, table of teams who can access)
*/

hook.Add("InitPostEntity", "load:comms", function()

    advancedComms.Functions.AddComms("nato", "[NATO]" ,Color(0,100,250), Color(255,255,255), {
        TEAM_NATOT, TEAM_USMCP, TEAM_USMCS, TEAM_USMCO, TEAM_USMCG, TEAM_USAFP, TEAM_USAFS, TEAM_USAFO, TEAM_USAFG, TEAM_USGBP, TEAM_USGBS, TEAM_USGBO, TEAM_USGBG, TEAM_SRRP, TEAM_SRRS, TEAM_SRRO, TEAM_SRRG, TEAM_RMPP, TEAM_RMPS, TEAM_RMPO, TEAM_RMPG, TEAM_SASP, TEAM_SASS, TEAM_SASO, TEAM_SASG, TEAM_NGOTA, TEAM_NATOGEN, TEAM_NATOMAJ, TEAM_NATOBRIG, TEAM_SOD, TEAM_RMP, TEAM_RMS, TEAM_RMO, TEAM_RMG, TEAM_NHC, TEAM_USMC1, TEAM_SAS1, TEAM_USAF1, TEAM_USGB1, TEAM_REP, TEAM_RES, TEAM_REO, TEAM_REG, TEAM_RE1, TEAM_RMP1, TEAM_NDS
    })

advancedComms.Functions.AddComms("csto", "[CSTO]" ,Color(230,50,0), Color(255,255,255), {
        TEAM_CSTOT, TEAM_RGFP, TEAM_RGFS, TEAM_RGFO, TEAM_RGFG, TEAM_RUAFP, TEAM_RUAFS, TEAM_RUAFO, TEAM_RUAFG, TEAM_RUMPP, TEAM_RUMPS, TEAM_RUMPO, TEAM_RUMPG, TEAM_SPETP, TEAM_SPETS, TEAM_SPETO, TEAM_SPETG, TEAM_SRFP, TEAM_SRFS, TEAM_SRFO, TEAM_SRFG, TEAM_CGOTA, TEAM_CSTOGEN, TEAM_CSTOMAJ, TEAM_CSTOBRIG, TEAM_SOD, TEAM_ASFP, TEAM_ASFS, TEAM_ASFO, TEAM_ASFG, TEAM_CHC, TEAM_RGF1, TEAM_RUAF1, TEAM_RUMP1, TEAM_SPET1, TEAM_ASF1, TEAM_RETP, TEAM_RETS, TEAM_RETO, TEAM_RETG, TEAM_RET1, TEAM_CDS
    })

    advancedComms.Functions.AddComms("open", "[OPEN COMMS]" ,Color(255,255,0), Color(255,255,255), {
        TEAM_NATOT, TEAM_USMCP, TEAM_USMCS, TEAM_USMCO, TEAM_USMCG, TEAM_USAFP, TEAM_USAFS, TEAM_USAFO, TEAM_USAFG, TEAM_USGBP, TEAM_USGBS, TEAM_USGBO, TEAM_USGBG, TEAM_SRRP, TEAM_SRRS, TEAM_SRRO, TEAM_SRRG, TEAM_RMPP, TEAM_RMPS, TEAM_RMPO, TEAM_RMPG, TEAM_SASP, TEAM_SASS, TEAM_SASO, TEAM_SASG, TEAM_NGOTA, TEAM_SOD, TEAM_CSTOT, TEAM_RGFP, TEAM_RGFS, TEAM_RGFO, TEAM_RGFG, TEAM_RUAFP, TEAM_RUAFS, TEAM_RUAFO, TEAM_RUAFG, TEAM_RUMPP, TEAM_RUMPS, TEAM_RUMPO, TEAM_RUMPG, TEAM_SPETP, TEAM_SPETS, TEAM_SPETO, TEAM_SPETG, TEAM_CGOTA, TEAM_CUST1, TEAM_CUST2, TEAM_NATOGEN, TEAM_NATOMAJ, TEAM_NATOBRIG, TEAM_CSTOGEN, TEAM_CSTOMAJ, TEAM_CSTOBRIG, TEAM_RMP, TEAM_RMS, TEAM_RMO, TEAM_RMG, TEAM_ASFP, TEAM_ASFS, TEAM_ASFO, TEAM_ASFG, TEAM_NHC, TEAM_CHC, TEAM_USMC1, TEAM_SAS1, TEAM_USAF1, TEAM_USGB1, TEAM_REP, TEAM_RES, TEAM_REO, TEAM_REG, TEAM_RE1, TEAM_RMP1, TEAM_NDS, TEAM_RGF1, TEAM_RUAF1, TEAM_RUMP1, TEAM_SPET1, TEAM_ASF1, TEAM_RETP, TEAM_RETS, TEAM_RETO, TEAM_RETG, TEAM_RET1, TEAM_CDS
    })

    advancedComms.Functions.AddComms("advert", "[ADVERT]" ,Color(255,255,0), Color(255,255,255), {
        TEAM_NATOT, TEAM_USMCP, TEAM_USMCS, TEAM_USMCO, TEAM_USMCG, TEAM_USAFP, TEAM_USAFS, TEAM_USAFO, TEAM_USAFG, TEAM_USGBP, TEAM_USGBS, TEAM_USGBO, TEAM_USGBG, TEAM_SRRP, TEAM_SRRS, TEAM_SRRO, TEAM_SRRG, TEAM_RMPP, TEAM_RMPS, TEAM_RMPO, TEAM_RMPG, TEAM_SASP, TEAM_SASS, TEAM_SASO, TEAM_SASG, TEAM_NGOTA, TEAM_SOD, TEAM_CSTOT, TEAM_RGFP, TEAM_RGFS, TEAM_RGFO, TEAM_RGFG, TEAM_RUAFP, TEAM_RUAFS, TEAM_RUAFO, TEAM_RUAFG, TEAM_RUMPP, TEAM_RUMPS, TEAM_RUMPO, TEAM_RUMPG, TEAM_SPETP, TEAM_SPETS, TEAM_SPETO, TEAM_SPETG, TEAM_SRFP, TEAM_SRFS, TEAM_SRFO, TEAM_SRFG, TEAM_CGOTA, TEAM_CUST1, TEAM_CUST2, TEAM_NATOGEN, TEAM_NATOMAJ, TEAM_NATOBRIG, TEAM_CSTOGEN, TEAM_CSTOMAJ, TEAM_CSTOBRIG, TEAM_RMP, TEAM_RMS, TEAM_RMO, TEAM_RMG, TEAM_ASFP, TEAM_ASFS, TEAM_ASFO, TEAM_ASFG, TEAM_NHC, TEAM_CHC, TEAM_USMC1, TEAM_SAS1, TEAM_USAF1, TEAM_USGB1, TEAM_REP, TEAM_RES, TEAM_REO, TEAM_REG, TEAM_RE1, TEAM_RMP1, TEAM_NDS, TEAM_RGF1, TEAM_RUAF1, TEAM_RUMP1, TEAM_SPET1, TEAM_ASF1, TEAM_RETP, TEAM_RETS, TEAM_RETO, TEAM_RETG, TEAM_RET1, TEAM_CDS
    })

    advancedComms.Functions.AddComms("ad", "[ADVERT]" ,Color(255,255,0), Color(255,255,255), {
        TEAM_NATOT, TEAM_USMCP, TEAM_USMCS, TEAM_USMCO, TEAM_USMCG, TEAM_USAFP, TEAM_USAFS, TEAM_USAFO, TEAM_USAFG, TEAM_USGBP, TEAM_USGBS, TEAM_USGBO, TEAM_USGBG, TEAM_SRRP, TEAM_SRRS, TEAM_SRRO, TEAM_SRRG, TEAM_RMPP, TEAM_RMPS, TEAM_RMPO, TEAM_RMPG, TEAM_SASP, TEAM_SASS, TEAM_SASO, TEAM_SASG, TEAM_NGOTA, TEAM_SOD, TEAM_CSTOT, TEAM_RGFP, TEAM_RGFS, TEAM_RGFO, TEAM_RGFG, TEAM_RUAFP, TEAM_RUAFS, TEAM_RUAFO, TEAM_RUAFG, TEAM_RUMPP, TEAM_RUMPS, TEAM_RUMPO, TEAM_RUMPG, TEAM_SPETP, TEAM_SPETS, TEAM_SPETO, TEAM_SPETG, TEAM_SRFP, TEAM_SRFS, TEAM_SRFO, TEAM_SRFG, TEAM_CGOTA, TEAM_CUST1, TEAM_CUST2, TEAM_NATOGEN, TEAM_NATOMAJ, TEAM_NATOBRIG, TEAM_CSTOGEN, TEAM_CSTOMAJ, TEAM_CSTOBRIG, TEAM_RMP, TEAM_RMS, TEAM_RMO, TEAM_RMG, TEAM_ASFP, TEAM_ASFS, TEAM_ASFO, TEAM_ASFG, TEAM_NHC, TEAM_CHC, TEAM_USMC1, TEAM_SAS1, TEAM_USAF1, TEAM_USGB1, TEAM_REP, TEAM_RES, TEAM_REO, TEAM_REG, TEAM_RE1, TEAM_RMP1, TEAM_NDS, TEAM_RGF1, TEAM_RUAF1, TEAM_RUMP1, TEAM_SPET1, TEAM_ASF1, TEAM_RETP, TEAM_RETS, TEAM_RETO, TEAM_RETG, TEAM_RET1, TEAM_CDS
    })

end)

/* 

By Editing any other file than the one supplied on the github, you are taking and editing my content without my permission. These files are the property of Jck and no permission is given to make edits or changes to their contents.

If you would like to change something, please ask me through steam.

*/